FROM elixir:alpine
ARG app_name=milk
ARG phoenix_subdir=.
ARG build_env=prod
ENV MIX_ENV=${build_env} TERM=xterm
ENV GOOGLE_APPLICATION_CREDENTIALS=e-players6814-8e8eac82841c.json
ENV GOOGLE_PROJECT_ID=e-players6814

WORKDIR /opt/app
RUN apk update \
  && apk --no-cache --update add nodejs nodejs-npm \
  && apk add alpine-sdk \
  && mix local.rebar --force \
  && mix local.hex --force